IQSS/dataverse-installations

- json2tsv.py
> add script to create TSV file from JSON data #5

- versions.py
> show versions of Dataverse from installations on map #3

- index.html
- js/map.js
Please see commit messages.
You can see it working at https://poikilotherm.github.io/dataverse-installations
Feedback appreciated.
> Testing marker clustering, fix some minors

- index.html
- js/map.js
Reverts IQSS/dataverse-installations#20
> Revert "Testing marker clustering, fix some minors"

- data/data.json
> update datasuds dataverse.ird.fr

- CONTRIBUTING.md
- README.md
Decided to do a pull request for #1 in case @pdurbin wants to comment or reject my re-write of README.md and CONTRIBUTING.md
I decided not to do a wiki, but combine README and CONTRIBUTING for documentation. Is this close to what you were thinking?
> Documentation updated

- data/data.json
> Add the IISH dataverse year of inception and other details

- data/data.json
> Change dataverse nl's info #33

- css/styles.css
- index.html
- js/table.js
It might help with #7 if we put the launch year on the table like in the screenshot below:
> add launch year to table #7

- css/styles.css
- js/map.js
- map.html
Changed map layer to CartoDB.Voyager, adjusted size and colors for dots [ref IQSS/dataverse.org/issues/66]
> Changed map layer to CartoDB.Voyager, adjusted size and colors for dots

- boards.py
> for installations with boards, print name and url #45

- data/data.json
> add country, year, etc for dadosabertos.rnp.br #42

- data/data.json
> Add Jülich DATA to the map.

- data/data.json
To add CoreTrust to DataverseNO #62
> DV-NO CoreTrust

- data/data.json
> Universidad de Chile

- data/data.json
> Open Forest Data

- data/data.json
> IIT Dataverse

- data/data.json
We have renamed to Borealis officially today, and have a new URL.
> Scholars Portal Dataverse renaming and new URL

- data/data.json
> added DATICE

- data/data.json
> Repositorio Polen

- data/data.json
Adding 
KU Leuven RDR Project Board to the Dataverse Installation Map
> KU Leuven RDR Project Board

- data/data.json
> NYCU Dataverse

- data/data.json
> AUSSDA CoreTrust Link

- data/data.json
> removed Yale-NUS Dataverse (not in DNS) #195

- data/data.json
> update Norway's contact address

- data/data.json
> add IDSC Dataverse

- data/data.json
> Added Yale

- data/data.json
Added about link to crowd-source spreadsheet, so had to re-run update-data.py
> add yale about

- data/data.json
> add TUData

- data/data.json
> Add UCLA description

- data/data.json
> removed awf entry - redirect

- data/data.json
> add wyoming wroclae - KU CTS

- README.md
- data/data.json
- update-data.py
This PR adds a field dv_hub_id that is unique to be able to track changes on each installation.
> Adds dv_hub_id UUID to the installations
